name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Iniciar sesión en Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 3: Construir y etiquetar la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t fabianrc2810/final-project:latest .
        docker tag fabianrc2810/final-project:latest fabianrc2810/final-project:${{ github.sha }}

    # Paso 4: Subir la imagen a Docker Hub
    - name: Push Docker image
      run: |
        docker push fabianrc2810/final-project:latest
        docker push fabianrc2810/final-project:${{ github.sha }}

    # Paso 5: Configurar el contexto de Kubernetes
    - name: Configure Kubernetes Context
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl get nodes

    # Paso 6: Aplicar el archivo de Deployment
    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f k8s/deployment.yml

    # Paso 7: Actualizar el Deployment con la nueva imagen
    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/final-project-deployment final-project-container=fabianrc2810/final-project:${{ github.sha }} --record
        kubectl rollout status deployment/final-project-deployment

    # Paso 8: Verificar los pods desplegados
    - name: Verify Deployment
      run: |
        kubectl get pods -l app=final-project
