name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npx eslint .

    - name: Run unit tests
      run: npm test

    - name: Build Docker image
      run: |
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        DATE=$(date +'%Y%m%d')
        IMAGE_TAG="$DATE-$COMMIT_SHA"
        docker build -t fabianrc2810/final-project:$IMAGE_TAG .

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        DATE=$(date +'%Y%m%d')
        IMAGE_TAG="$DATE-$COMMIT_SHA"
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag fabianrc2810/final-project:$IMAGE_TAG fabianrc2810/final-project:$IMAGE_TAG
        docker push fabianrc2810/final-project:$IMAGE_TAG
